name: Dev Environment - Scheduled API Tests

on:
  # Schedule to run daily at 6:00 AM UTC
  schedule:
    - cron: '0 6 * * *'
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  api-tests-dev:
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run API Tests - Dev Environment
        env:
          BASE_URL: 'https://petstore.swagger.io'
          API_VERSION: '/v2'
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: npx playwright test

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-dev
          path: playwright-report/
          retention-days: 30

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-dev
          path: test-results/
          retention-days: 30

      - name: Notify on Failure
        if: failure()
        run: |
          echo "⚠️ Dev environment tests failed!"
          echo "Check the test report for details"
